# Generated by Django 2.2.7 on 2019-11-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
