# Generated by Django 2.2.7 on 2019-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anon',
            field=models.BooleanField(default=True),
        ),
    ]
